# Project Setup
general:
  pipeline: "sap-cloud-sdk"

# Stage enablement
stages:
  testStage:
    enable: true
  malwareScanStage:
    enable: true
  deployStage:
    enable: true
  tmsStage:
    enable: true


# Stage configuration
steps:
  mtaBuild:
    applicationName: "CICDsample" # optional

# Stage enablement
stages:
  testStage:
    enable: true

# Stage enablement
stages:
  malwareScanStage:
    enable: true
    
# Stage enablement
stages:
  deployStage:
    enable: true

# Stage configuration
steps:
  cloudFoundryDeploy:
    cloudFoundry:
      apiEndpoint: "https://api.cf.us10.hana.ondemand.com"
      org: "7cf42125trial"
      space: "dev"
      credentialsId: "cf-ls-login"
      
# # Stage enablement
# stages:
#   tmsStage:
#     enable: true

# # Stage configuration
# steps:
#   tmsUpload:
#     nodeName: "qas-tms"
#     credentialsId: "qas-tms-credential-info"
