# Project Setup
general:
  pipeline: "sap-cloud-sdk"

# Stage build and
stages:
  testStage:
    enable: true
  malwareScanStage:
    enable: true
  deployStage:
    enable: true
  tmsStage:
    enable: true


# Stage build
steps:
  mtaBuild:
    applicationName: "CICDsample"
stages:
  testStage:
    enable: true

# Stage enablement
stages:
  malwareScanStage:
    enable: true
    
# Stage enablement
stages:
  deployStage:
    enable: true

stages:
  productionDeployment:
    cfTargets:
    - org: "7cf42125trial"
      space: "dev"
      appName: "sampleSAPCICD"
      apiEndpoint: "https://api.cf.us10.hana.ondemand.com"
      credentialsId: "cf-ls-login"

# # Stage deploy
# steps:
#   cloudFoundryDeploy:
#     cloudFoundry:
#       apiEndpoint: "https://api.cf.us10.hana.ondemand.com"
#       org: "7cf42125trial"
#       space: "dev"
#       credentialsId: "cf-ls-login"
#
# Stage tms
# stages:
#   tmsStage:
#     enable: true

steps:
  tmsUpload:
    nodeName: "DEV_node"
    credentialsId: "dev-tms-service-key"
